# Generated by Django 3.2.12 on 2022-04-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название места')),
                ('description_short', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Полное описание')),
                ('coordinates_lng', models.DecimalField(blank=True, decimal_places=14, max_digits=16, verbose_name='Долгота')),
                ('coordinates_lat', models.DecimalField(blank=True, decimal_places=14, max_digits=16, verbose_name='Широта')),
            ],
        ),
    ]
