# Generated by Django 3.2.12 on 2022-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='detailsUrl',
            field=models.CharField(blank=True, max_length=200, verbose_name='Путь к JSON-файлу с деталями'),
        ),
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(blank=True, max_length=200, verbose_name='Уникальный идентификатор места'),
        ),
        migrations.AddField(
            model_name='place',
            name='project_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название проекта места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название места'),
        ),
    ]
