# Generated by Django 4.0.3 on 2022-04-06 06:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['placeId'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
    ]
