# Generated by Django 4.0.3 on 2022-04-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_options_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='placeId',
        ),
        migrations.RemoveField(
            model_name='place',
            name='project_title',
        ),
    ]
